version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=skywalkingDb
      #- discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Shanghai
    volumes:
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
  es-head:
    image: docker.io/mobz/elasticsearch-head:5
    container_name: es-head
    ports:
      - 9100:9100
    links:
      - elasticsearch
  oap:
    image: apache/skywalking-oap-server:6.5.0
    container_name: oap
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      TZ: Asia/Shanghai
  ui:
      image: apache/skywalking-ui:6.5.0
      container_name: ui
      depends_on:
        - oap
      links:
        - oap
      restart: always
      ports:
        - 18080:8080
      environment:
        SW_OAP_ADDRESS: oap:12800
        TZ: Asia/Shanghai