version: '3'

services:
  mysql:
    image: mysql:5.7.23
    ports:
      - 3306:3306
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: 12345678
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: 123456
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: blog-mysql
  wordpress:
    depends_on:
       - mysql
    image: wordpress
    restart: always
    ports:
      - 6379:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 123456
    volumes:
      - /var/www/html:/var/www/html
    container_name: blog-wordpress