version: '2.0'

services:
  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - 8080:80
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - /var/log/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - ./domain:/etc/nginx/domain
