version: '2'
services:
  consul:
    image: consul
    container_name: consul_agent
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 53:53/udp
    volumes:
      - ./data:/consul/data
      - ./config:/consul/config
