version: '3'
services:

  nginx1:
    image: 'nginx'
    restart: always
    container_name: 'nginx1'
    links:
      - trigger1:trigger1
    extra_hosts:
      - "api-scheduler.vipkid-qa.com.cn:10.33.1.11"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf/conf.d/:/etc/nginx/conf.d/
      - ./nginx-conf/logs/:/var/log/nginx/
      - ./nginx-conf/scheduler-cms/:/scheduler-cms/
    ports:
      - '80:80'

  web1:
    image: 'web:v0.1'
    restart: always
    container_name: web1
    extra_hosts:
      - "api-scheduler.vipkid-qa.com.cn:10.33.1.11"
    ports:
      - '8090:8080'


  trigger3:
    image: 'trigger:v21'
    restart: always
    container_name: trigger3
    extra_hosts:
      - "api-scheduler.vipkid-qa.com.cn:10.33.1.11"
    ports:
      - '8083:8080'

  trigger2:
    image: 'trigger:v21'
    restart: always
    container_name: trigger2
    extra_hosts:
      - "api-scheduler.vipkid-qa.com.cn:10.33.1.11"
    ports:
      - '8082:8080'

  trigger1:
    image: 'trigger:v21'
    restart: always
    container_name: trigger1
    extra_hosts:
      - "api-scheduler.vipkid-qa.com.cn:10.33.1.11"
    ports:
      - '8080:8080'


networks:
  default:
    external:
      name: hezk

