version: '3'
services:


  exporter:
    container_name: mysql-exporter-dev
    image: prom/mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=root:123456@(mysql:3306)/

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "20001:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://10.33.1.11:20002
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "20002:3000"
    volumes:
      - ./grafana:/var/lib/grafana

networks:
  default:
    external:
      name: hezk

