version: '3'
services:

  shell1:
    image: 'shell:v0.3'
    restart: always
    container_name: shell1
    command: '/opt/vipkid/application/main --project=project-1 --profile=test'
    extra_hosts:
      - "api-scheduler.vipkid-qa.com.cn:10.33.1.11"

  shell2:
    image: 'shell:v0.3'
    restart: always
    container_name: shell2
    command: '/opt/vipkid/application/main --project=project-1 --profile=test'
    extra_hosts:
      - "api-scheduler.vipkid-qa.com.cn:10.33.1.11"

  shell3:
    image: 'shell:v0.3'
    restart: always
    container_name: shell3
    command: '/opt/vipkid/application/main --project=project-1 --profile=test'
    extra_hosts:
      - "api-scheduler.vipkid-qa.com.cn:10.33.1.11"

  shell4:
    image: 'shell:v0.3'
    restart: always
    container_name: shell4
    command: '/opt/vipkid/application/main --project=project-1 --profile=test'
    extra_hosts:
      - "api-scheduler.vipkid-qa.com.cn:10.33.1.11"

  shell5:
    image: 'shell:v0.3'
    restart: always
    container_name: shell5
    command: '/opt/vipkid/application/main --project=project-1 --profile=test'
    extra_hosts:
      - "api-scheduler.vipkid-qa.com.cn:10.33.1.11"

  shell6:
    image: 'shell:v0.3'
    restart: always
    container_name: shell6
    command: '/opt/vipkid/application/main --project=project-1 --profile=test'
    extra_hosts:
      - "api-scheduler.vipkid-qa.com.cn:10.33.1.11"

  shell7:
    image: 'shell:v0.3'
    restart: always
    container_name: shell7
    command: '/opt/vipkid/application/main --project=project-1 --profile=test'
    extra_hosts:
      - "api-scheduler.vipkid-qa.com.cn:10.33.1.11"

  shell8:
    image: 'shell:v0.3'
    restart: always
    container_name: shell8
    command: '/opt/vipkid/application/main --project=project-1 --profile=test'
    extra_hosts:
      - "api-scheduler.vipkid-qa.com.cn:10.33.1.11"
      
networks:
  default:
    external:
      name: hezk

